format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$character"""

right_format = """
$git_branch\
"""

add_newline = false
palette = "catppuccin_mocha"

[os]
disabled = true
format = '[$symbol ]($style)'
style = 'fg:grey2'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = false
style_root = 'fg:red'
style_user = 'fg:blue'
format = '[$user]($style)'

[hostname]
ssh_only = false
style = 'fg:blue'
format = '[  $hostname]($style) '

[directory]
style = "fg:orange"
read_only_style = "fg:orange"
truncation_length = 3
truncation_symbol = "…/"
format = "[ $path]($style)[$read_only]($read_only_style) "

[git_branch]
style = "fg:green"
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
