gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - "#f5e0dc" # rosewater
      - bold
    inactiveBorderColor:
      - "#a6adc8" # subtext0
    optionsTextColor:
      - "#89b4fa" # blue
    selectedLineBgColor:
      - "#313244" # surface0
    selectedRangeBgColor:
      - "#313244" # surface0
    cherryPickedCommitBgColor:
      - "#45475a" # surface1
    cherryPickedCommitFgColor:
      - "#f5c2e7" # pink
    unstagedChangesColor:
      - "#f38ba8" # red
