start-at-login = true

after-login-command = []

after-startup-command = [
  'exec-and-forget sketchybar',
  'exec-and-forget borders',
]
exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  '/opt/homebrew/opt/sketchybar/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

on-focus-changed = [
  'exec-and-forget /opt/homebrew/opt/sketchybar/bin/sketchybar --trigger aerospace_focus_change',
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'calculator'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'iphone'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'settings'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'arc'
run = 'move-node-to-workspace 1 --focus-follows-window'

[[on-window-detected]]
if.app-name-regex-substring = 'ghostty'
run = 'move-node-to-workspace 2 --focus-follows-window'

[[on-window-detected]]
if.app-name-regex-substring = 'claude'
run = 'move-node-to-workspace 3 --focus-follows-window'

[[on-window-detected]]
if.app-name-regex-substring = 'slack'
run = 'move-node-to-workspace 4 --focus-follows-window'

[[on-window-detected]]
if.app-name-regex-substring = 'discord'
run = 'move-node-to-workspace 4 --focus-follows-window'

[[on-window-detected]]
if.app-name-regex-substring = 'obsidian'
run = 'move-node-to-workspace 5 --focus-follows-window'

[[on-window-detected]]
if.app-name-regex-substring = 'music'
run = 'move-node-to-workspace 6 --focus-follows-window'

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 12
outer.bottom = 10
outer.top = 22
outer.right = 12

[mode.main.binding]

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-shift-f = 'fullscreen'
alt-shift-m = 'focus-monitor next'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'

alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
alt-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
alt-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-semicolon = 'mode service'

alt-b = 'exec-and-forget open -a /Applications/Arc.app'
alt-n = 'exec-and-forget open -a /Applications/Obsidian.app'
alt-t = 'exec-and-forget open -a /Applications/Ghostty.app'
alt-a = 'exec-and-forget open -a /Applications/Claude.app'
alt-m = 'exec-and-forget open -a /System/Applications/Music.app'
alt-s = 'exec-and-forget open -a /Applications/Slack.app'
alt-d = 'exec-and-forget open -a /Applications/Discord.app'


[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = [
  'layout floating tiling',
  'mode main',
] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']
